name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", 3.12", "3.12", "3.13" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml

      - name: Install project (with test extras)
        run: |
          python -m pip install --upgrade pip wheel build
          pip install -e .[test]

      - name: Lint with Ruff
        run: |
          ruff --version
          ruff check .

      - name: Run tests
        run: |
          pytest -q

  build:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip build twine
          pip install -e .[test]

      - name: Build sdist & wheel
        run: python -m build

      - name: Twine check
        run: twine check dist/*
